// SPDX-FileCopyrightText: Copyright 2026 The SLSA Authors
// SPDX-License-Identifier: Apache-2.0

package gha

import (
	"fmt"
	"strings"

	gogithub "github.com/google/go-github/v90/github"
	intoto "github.com/in-toto/attestation/go/v1"
	buildv1 "github.com/slsa-framework/protos/build/v1"
	"google.golang.org/protobuf/types/known/structpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// BuildType is the SLSA build type URI for provenance generated by watching a
// build system run from the outside.
const BuildType = "https://slsa.dev/buildtypes/watcher/v1"

// Predicate renders the watched run as a SLSA build provenance v1 predicate.
// The builder is the workflow that ran; the source repository at the run's
// commit is recorded as a resolved dependency. The inputs (from RunInputs)
// are the triggerer-controlled workflow inputs and are recorded in the
// external parameters.
func (c *Client) Predicate(run *gogithub.WorkflowRun, inputs map[string]any) (*buildv1.Provenance, error) {
	repoURI := fmt.Sprintf("https://github.com/%s/%s", c.Owner, c.Repo)

	externalParams := map[string]any{
		"workflow":   run.GetPath(),
		"repository": repoURI,
		"ref":        headRef(run),
		"event":      run.GetEvent(),
	}
	if len(inputs) > 0 {
		externalParams["inputs"] = inputs
	}
	external, err := structpb.NewStruct(externalParams)
	if err != nil {
		return nil, fmt.Errorf("building external parameters: %w", err)
	}

	pred := &buildv1.Provenance{
		BuildDefinition: &buildv1.BuildDefinition{
			BuildType:          BuildType,
			ExternalParameters: external,
			ResolvedDependencies: []*intoto.ResourceDescriptor{{
				Uri:    fmt.Sprintf("git+%s@%s", repoURI, headRef(run)),
				Digest: map[string]string{"gitCommit": run.GetHeadSHA()},
			}},
		},
		RunDetails: &buildv1.RunDetails{
			Builder: &buildv1.Builder{
				Id: fmt.Sprintf("%s/%s@%s", repoURI, run.GetPath(), headRef(run)),
			},
			Metadata: &buildv1.BuildMetadata{
				InvocationId: fmt.Sprintf("%s/actions/runs/%d/attempts/%d", repoURI, run.GetID(), run.GetRunAttempt()),
			},
		},
	}
	if t := run.GetRunStartedAt(); !t.IsZero() {
		pred.RunDetails.Metadata.StartedOn = timestamppb.New(t.Time)
	}
	if t := run.GetUpdatedAt(); !t.IsZero() {
		pred.RunDetails.Metadata.FinishedOn = timestamppb.New(t.Time)
	}
	return pred, nil
}

// headRef returns the fully-qualified git ref the run built, falling back to
// the head commit when the branch is not known.
func headRef(run *gogithub.WorkflowRun) string {
	if branch := run.GetHeadBranch(); branch != "" {
		if strings.HasPrefix(branch, "refs/") {
			return branch
		}
		return "refs/heads/" + branch
	}
	return run.GetHeadSHA()
}
