// SPDX-FileCopyrightText: Copyright 2026 The SLSA Authors
// SPDX-License-Identifier: Apache-2.0

package gha

import (
	"context"
	"fmt"
	"os"
	"strings"

	gogithub "github.com/google/go-github/v90/github"
	intoto "github.com/in-toto/attestation/go/v1"
	buildv1 "github.com/slsa-framework/protos/build/v1"
	"google.golang.org/protobuf/types/known/structpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// BuildType is the SLSA build type URI for provenance generated by watching a
// build system run from the outside.
const BuildType = "https://slsa.dev/buildtypes/watcher/v1"

// Predicate renders the watched run as a SLSA build provenance v1 predicate.
// The builder is the workflow that ran; the source repository at the run's
// commit is recorded as a resolved dependency. The ref (from RunRef) and the
// inputs (from RunInputs) are recorded in the external parameters.
func (c *Client) Predicate(run *gogithub.WorkflowRun, ref string, inputs map[string]any) (*buildv1.Provenance, error) {
	repoURI := fmt.Sprintf("https://github.com/%s/%s", c.Owner, c.Repo)

	externalParams := map[string]any{
		"workflow":   run.GetPath(),
		"repository": repoURI,
		"ref":        ref,
		"event":      run.GetEvent(),
	}
	if len(inputs) > 0 {
		externalParams["inputs"] = inputs
	}
	external, err := structpb.NewStruct(externalParams)
	if err != nil {
		return nil, fmt.Errorf("building external parameters: %w", err)
	}

	pred := &buildv1.Provenance{
		BuildDefinition: &buildv1.BuildDefinition{
			BuildType:          BuildType,
			ExternalParameters: external,
			ResolvedDependencies: []*intoto.ResourceDescriptor{{
				Uri:    fmt.Sprintf("git+%s@%s", repoURI, ref),
				Digest: map[string]string{"gitCommit": run.GetHeadSHA()},
			}},
		},
		RunDetails: &buildv1.RunDetails{
			Builder: &buildv1.Builder{
				Id: fmt.Sprintf("%s/%s@%s", repoURI, run.GetPath(), ref),
			},
			Metadata: &buildv1.BuildMetadata{
				InvocationId: fmt.Sprintf("%s/actions/runs/%d/attempts/%d", repoURI, run.GetID(), run.GetRunAttempt()),
			},
		},
	}
	if t := run.GetRunStartedAt(); !t.IsZero() {
		pred.RunDetails.Metadata.StartedOn = timestamppb.New(t.Time)
	}
	if t := run.GetUpdatedAt(); !t.IsZero() {
		pred.RunDetails.Metadata.FinishedOn = timestamppb.New(t.Time)
	}
	return pred, nil
}

// RunRef returns the fully-qualified git ref the run built. Inside the
// attested run the runner's own GITHUB_REF is exact. For other runs the ref
// name is resolved through the git refs API, because the runs API reports a
// tag's name in head_branch, indistinguishable from a branch. When nothing
// resolves, the name is assumed to be a branch; with no name at all the head
// commit is returned.
func (c *Client) RunRef(ctx context.Context, run *gogithub.WorkflowRun) string {
	if c.sameRun() {
		if ref := os.Getenv(envRef); ref != "" {
			return ref
		}
	}

	name := run.GetHeadBranch()
	if name == "" {
		return run.GetHeadSHA()
	}
	if strings.HasPrefix(name, "refs/") {
		return name
	}
	if ref, _, err := c.gh.Git.GetRef(ctx, c.Owner, c.Repo, "heads/"+name); err == nil &&
		ref.GetObject().GetSHA() == run.GetHeadSHA() {
		return "refs/heads/" + name
	}
	if _, _, err := c.gh.Git.GetRef(ctx, c.Owner, c.Repo, "tags/"+name); err == nil {
		return "refs/tags/" + name
	}
	return "refs/heads/" + name
}
